x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "$TAG"
  publishedVersionMetadata:
    releaseNote: >-
      Initial release.
    releaseTypes:
      - Feature
    recommended: false

#  images:
#    '':
#      properties:
#        sdk-jupyter.image.repo:
#          type: REPO_WITH_REGISTRY
#        sdk-jupyter.image.tag:
#          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE

required:
  - name
  - namespace

