apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .Release.Name }}
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
  annotations:
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "partner", "product_id": "wordpress", "partner_name": "Partner"}'
spec:
  descriptor:
    type: SDK
    version: '2.3'
{{/*  info:*/}}
{{/*  {{ if .Values.enablePublicServiceAndIngress -}}*/}}
{{/*    - name: Jupyter Notebook Webserver address*/}}
{{/*      type: Reference*/}}
{{/*      valueFrom:*/}}
{{/*        ingressRef:*/}}
{{/*          name: {{ .Release.Name }}-service*/}}
{{/*          protocol: HTTPS*/}}
{{/*  {{- else -}}*/}}
{{/*    - name: Forward Jupyter Notebook Webserver port locally*/}}
{{/*      value: kubectl port-forward --namespace {{ .Release.Namespace }} svc/{{ .Release.Name }}-service 8888:8888*/}}
{{/*    - name: Jupyter Notebook Webserver address (local only)*/}}
{{/*      value: "http://localhost:8888/"*/}}
{{/*  {{- end }}*/}}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  addOwnerRef: true
  componentKinds:
    - group: v1
      kind: Secret
    - group: v1
      kind: Service
    {{ if .Values.enablePublicServiceAndIngress }}
    - group: networking.k8s.io
      kind: Ingress
    {{ end }}
    - group: apps/v1
      kind: Deployment
