apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sdk
  labels: &SdkDeploymentLabels
    app: "{{ .Release.Name }}"
    name: "{{ .Release.Name }}"
spec:
  selector:
    matchLabels: *SdkDeploymentLabels
  replicas: 1
  template:
    metadata:
      labels: *SdkDeploymentLabels
    spec:
      {{- if .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.containerSecurityContext | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ .Values.serviceAccountName }}"
      containers:
        - name: sdk
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          envFrom:
            - secretRef:
              {{- if .Values.secretRef}}
                name: {{ .Values.secretRef }}
              {{- else}}
                name: {{ .Release.Name }}-secret
              {{- end}}
