{{ if .Values.enablePublicServiceAndIngress }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
spec:
  tls:
    - secretName: {{ .Release.Name }}-web-tls
  defaultBackend:
    service:
      name: {{ .Release.Name }}-service
      port:
        name: http
{{- end }}
