{{- if not .Values.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "synthesized-sdk.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: "{{ include "synthesized-sdk.fullname" . }}"
    app.kubernetes.io/component: synthesized-sdk
type: Opaque
data:
{{- $tplConfig  := .Values.tplConfig -}}
{{- range $k, $v := .Values.envRenderSecret }}
  {{- if $tplConfig }}
  {{ $k }}: {{ tpl $v $ | b64enc | quote }}
  {{- else }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
