apiVersion: v1
kind: Service
metadata:
  name: {{ include "synthesized-sdk.fullname" . }}-service
  labels: &SdkServiceLabels
    app: {{ include "synthesized-sdk.fullname" . }}
    name: {{ include "synthesized-sdk.fullname" . }}
spec:
  selector: *SdkServiceLabels
  ports:
    - name: web
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30001
  type: NodePort
