{{- if .Values.enablePublicServiceAndIngress }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-tls
  labels:
    app: {{ .Release.Name }}
    name: {{ .Release.Name }}
data:
  tls.key: |
    {{- .Values.tls.base64EncodedPrivateKey | nindent 4 }}
  tls.crt: |
    {{- .Values.tls.base64EncodedCertificate | nindent 4 }}
type: kubernetes.io/tls
{{- end }}
